office_management_system/main_app/urls.py
from django.urls import path

from main_app import views, manager_views, employer_views
from . import hod_views

urlpatterns = [
    path("", views.login_page, name='login_page'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("admin_view_profile/", hod_views.admin_view_profile, name='admin_view_profile'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    # admin URL
    path("employer/add/", hod_views.add_employer, name='add_employer'),
    path("todolist/add/", hod_views.add_todolist, name='add_todolist'),
    path("manager/add/", hod_views.add_manager, name='add_manager'),
    path("manager/manage/", hod_views.manage_manager, name='manage_manager'),
    path("employer/manage/", hod_views.manage_employer, name='manage_employer'),
    path("todolist/manage/", hod_views.manage_todolist, name='manage_todolist'),
    path("todolist/delete/<int:todo_id>/", hod_views.delete_todolist, name='delete_todolist'),
    path("todolist/update/<int:todo_id>/", hod_views.update_todolist, name='update_todolist'),
    path("meeting/create/", hod_views.create_meeting, name='create_meeting'),
    path("department/manage/", hod_views.manage_department, name='manage_department'),
    path("meeting/manage/", hod_views.manage_meeting, name='manage_meeting'),
    path("department/add/", hod_views.add_department, name='add_department'),
    path("department/edit/<int:department_id>/", hod_views.edit_department, name='edit_department'),
    path("department/delete/<int:department_id>/", hod_views.delete_department, name='delete_department'),
    path("check_email_availability/", hod_views.check_email_availability, name="check_email_availability"),
    path("manager/edit/<int:manager_id>/", hod_views.edit_manager, name='edit_manager'),
    path("manager/delete/<int:manager_id>/", hod_views.delete_manager, name='delete_manager'),
    path('employer/edit/<int:employer_id>/', hod_views.edit_employer, name='edit_employer'),
    path("employer/delete/<int:employer_id>/", hod_views.delete_employer, name='delete_employer'),
    path('meeting/edit/<int:meeting_id>/', hod_views.edit_meeting, name='edit_meeting'),
    path("meeting/delete/<int:meeting_id>/", hod_views.delete_meeting, name='delete_meeting'),
    path("task/add/", hod_views.add_task, name='add_task'),
    path("task/manage/", hod_views.manage_task, name='manage_task'),
    path('task/edit/<int:task_id>/', hod_views.edit_task, name='edit_task'),
    path('task/update/<int:task_id>/', hod_views.update_task_status, name='update_task_status'),
    path("task/delete/<int:task_id>/", hod_views.delete_task, name='delete_task'),
    path('meeting/filter_participants/', hod_views.filter_participants, name='filter_participants'),
    path("admin_receive_message/", hod_views.admin_receive_message,
         name="admin_receive_message",),
    path("admin_notify_manager/", hod_views.admin_notify_manager,
         name='admin_notify_manager'),
    path("send_manager_notification/", hod_views.send_manager_notification,
         name='send_manager_notification'),
    path("admin_notify_employer/", hod_views.admin_notify_employer,
         name='admin_notify_employer'),
    path("send_mployer_notification/", hod_views.send_employer_notification,
         name='send_employer_notification'),
    # path('display_admin_meeting/', hod_views.display_admin_meeting, name='display_admin_meeting'),





    #
    # # manager URL
    path("manager/home/", manager_views.manager_home, name='manager_home'),
    path("manager/view/profile/", manager_views.manager_view_profile,
         name='manager_view_profile'),
    path("manager/todolist/add/", manager_views.add_todolist_manager, name='add_todolist_manager'),
    path("manager/todolist/manage/", manager_views.manage_todolist_manager, name='manage_todolist_manager'),
    path("manager/todolist/delete/<int:todo_id>/", manager_views.delete_todolist_manager, name='delete_todolist_manager'),
    path("manager/todolist/update/<int:todo_id>/", manager_views.update_todolist_manager, name='update_todolist_manager'),
    path("manager/task/add/", manager_views.add_task_manager, name='add_task_manager'),
    path("manager/task/manage/", manager_views.manage_task_manager, name='manage_task_manager'),
    path('manager/task/edit/<int:task_id>/', manager_views.edit_task_manager, name='edit_task_manager'),
    path("manager/task/delete/<int:task_id>/", manager_views.delete_task_manager, name='delete_task_manager'),
    path("manager/meeting/create/", manager_views.create_meeting_manager, name='create_meeting_manager'),
    path('manager/meeting/edit/<int:meeting_id>/', manager_views.edit_meeting_manager, name='edit_meeting_manager'),
    path("manager/meeting/delete/<int:meeting_id>/", manager_views.delete_meeting_manager, name='delete_meeting_manager'),
    path("manager/meeting/manage/", manager_views.manage_meeting_manager, name='manage_meeting_manager'),
    path('manager/meeting/filter_participants_manager/', manager_views.filter_participants_manager, name='filter_participants_manager'),
    path("manager/fcmtoken/", manager_views.manager_fcmtoken, name='manager_fcmtoken'),
    path("manager/view/notification/", manager_views.manager_view_notification,
         name="manager_view_notification"),
    path('manager/mytask/update/<int:task_id>/', manager_views.update_mytask, name='update_mytask'),
    path('manager/display_user_tasks/', manager_views.display_user_tasks, name='display_user_tasks'),
    path('manager/display_user_meeting/', manager_views.display_user_meeting, name='display_user_meeting'),
    path('manager/receive_message/', manager_views.receive_message, name='receive_message'),
    path('manager/send_message/', manager_views.send_message, name='send_message'),
    path('manager/delete_send_message/<int:message_id>/', manager_views.manager_delete_send_message, name='manager_delete_send_message'),
    path('manager/send_message/edit/<int:message_id>/', manager_views.manager_edit_message, name='manager_edit_message'),
    path('manager/clear_send_messages/', manager_views.clear_send_messages, name='clear_send_messages'),
    path('manager/project/create/', manager_views.manager_create_project, name='manager_create_project'),
    path('manager/project/manage/', manager_views.manager_manage_project, name='manager_manage_project'),
    path('manager/project/edit/<int:project_id>/', manager_views.manager_edit_project, name='manager_edit_project'),
    path('manager/project/delete/<int:project_id>/', manager_views.manager_delete_project, name='manager_delete_project'),
    path('manager/project/upload/<int:project_id>', manager_views.upload_file, name='upload_file'),
    path('manager/project/<int:project_id>/files/', manager_views.project_files, name='project_files'),
    path("manager/file/delete/<int:file_id>/", manager_views.manager_delete_file, name='manager_delete_file'),

    # # employer URL
    path("employer/home/", employer_views.employer_home, name='employer_home'),
    path("employer/view/profile/", employer_views.employer_view_profile,
         name='employer_view_profile'),
    path("employer/fcmtoken/", employer_views. employer_fcmtoken, name='employer_fcmtoken'),
    path("employer/view/notification/", employer_views.employer_view_notification,
         name="employer_view_notification"),
    path('employer/employer_receive_message/', employer_views.employer_receive_message, name='employer_receive_message'),
    path('employer/employer_send_message/', employer_views.employer_send_message, name='employer_send_message'),
    path('employer/employer_delete_send_message/<int:message_id>/', employer_views.employer_delete_send_message, name='employer_delete_send_message'),
    path('employer/employer_send_message/edit/<int:message_id>/', employer_views.employer_edit_message, name='employer_edit_message'),
    path('employer/employer_clear_send_messages/', employer_views.employer_clear_send_messages, name='employer_clear_send_messages'),
    path("employer/todolist/add/", employer_views.add_todolist_employer, name='add_todolist_employer'),
    path("employer/todolist/manage/", employer_views.manage_todolist_employer, name='manage_todolist_employer'),
    path("employer/todolist/delete/<int:todo_id>/", employer_views.delete_todolist_employer, name='delete_todolist_employer'),
    path("employer/todolist/update/<int:todo_id>/", employer_views.update_todolist_employer, name='update_todolist_employer'),
    path("employer/meeting/create/", employer_views.create_meeting_employer, name='create_meeting_employer'),
    path('employer/meeting/edit/<int:meeting_id>/', employer_views.edit_meeting_employer, name='edit_meeting_employer'),
    path("employer/meeting/delete/<int:meeting_id>/", employer_views.delete_meeting_employer, name='delete_meeting_employer'),
    path("employer/meeting/manage/", employer_views.manage_meeting_employer, name='manage_meeting_employer'),
    path('employer/meeting/filter_participants_employer/', employer_views.filter_participants_employer, name='filter_participants_employer'),
    path('employer/display_employer_meeting/', employer_views.display_employer_meeting, name='display_employer_meeting'),
    path('employer/update_employer_task/update/<int:task_id>/', employer_views.update_employer_task, name='update_employer_task'),
    path('employer/display_employer_tasks/', employer_views.display_employer_tasks, name='display_employer_tasks'),
    path('employer/project/display_projects_team/', employer_views.display_projects_team, name='display_projects_team'),
    path('employer/project/upload/<int:project_id>', employer_views.employer_upload_file, name='employer_upload_file'),

office_management_system/office_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path("", include('main_app.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

office_management_system/main_app/models.py
import uuid
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import UserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = CustomUser(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        assert extra_fields["is_staff"]
        assert extra_fields["is_superuser"]
        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    USER_TYPE = ((1, "HOD"), (2, "Manager"), (3, "Employer"))
    GENDER = [("M", "Male"), ("F", "Female")]

    username = None  # Removed username, using email instead
    email = models.EmailField(unique=True)
    user_type = models.CharField(default=1, choices=USER_TYPE, max_length=1)
    gender = models.CharField(max_length=1, choices=GENDER)
    profile_pic = models.ImageField()
    address = models.TextField()
    fcm_token = models.TextField(default="")  # For firebase notifications
    job_title = models.CharField(max_length=100)  # New field: Job title
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.last_name + ", " + self.first_name


class Admin(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)


class Department(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Manager(models.Model):
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING, null=True, blank=False)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.admin.last_name + " " + self.admin.first_name


class Employer(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING, null=True, blank=False)

    def __str__(self):
        return self.admin.last_name + ", " + self.admin.first_name


class Project(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    project_manager = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    Project_team = models.ManyToManyField(Employer, related_name='projects')

    def __str__(self):
        return self.name


class TodoList(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    description = models.TextField()
    status = models.BooleanField(default=False)
    due_date = models.DateField()
    due_time = models.TimeField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    manager = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='managed_tasks')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    description = models.TextField()
    due_date = models.DateField()
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Meeting(models.Model):
    title = models.CharField(max_length=120)
    organizer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    description = models.TextField()
    time = models.TimeField()
    date = models.DateField()
    participants = models.ManyToManyField(CustomUser, related_name='meetings')

    def __str__(self):
        return self.title


class Message(models.Model):
    receiver = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='receiver_messages')
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sender_messages')
    message = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cleared = models.BooleanField(default=False)


class NotificationManagers(models.Model):
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    managers = models.ForeignKey(Manager, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NotificationEmployers(models.Model):
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    employers = models.ForeignKey(Employer, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class File(models.Model):
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='project_files/{project_id}/')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='documents')
    uploaded_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Admin.objects.create(admin=instance)
        if instance.user_type == 2:
            Manager.objects.create(admin=instance)
        if instance.user_type == 3:
            Employer.objects.create(admin=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.save()
    if instance.user_type == 2:
        instance.manager.save()
    if instance.user_type == 3:
        instance.employer.save()

office_management_system/main_app/templates/employer_template/create_meetingE_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{ page_title }}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <!-- Filter Participants Form -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">Filter Participants</h3>
                    </div>
                    <div class="card-body">
                        <!-- Filter Participants Form -->
                        <form id="filter-participants-form" method="post" action="{% url 'filter_participants_employer' %}">
                            {% csrf_token %}
                            {{ filter_form.as_p }}
                            <button type="submit" class="btn btn-primary">Filter Participants</button>
                        </form>

                        <!-- Participant Select -->
                        <select id="participants-select" class="form-control" multiple>
                            <!-- Selected participants will be dynamically added here -->
                        </select>

                        <!-- Add Participants Button -->
                        <div class="mt-3">
                            <button id="add-participants-btn" class="btn btn-primary">Add Participants</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <!-- Create Meeting Form -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">Create Meeting</h3>
                    </div>
                    <div class="card-body">
                        <form id="create-meeting-form" method="post" action="{% url 'create_meeting_employer' %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'dist/js/meeting_form.js' %}"></script>

{% endblock content %}

office_management_system/main_app/templates/employer_template/edit_meeting_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Edit Meeting"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

office_management_system/main_app/templates/employer_template/edit_todo_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Edit Task"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

office_management_system/main_app/templates/employer_template/employer_Receiver_messages.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block content %}
<section class="content">
                    <!-- Display received messages -->
                    <div class="card-body">
                        <h4>Received Messages</h4>
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Sender</th>
                                    <th>Message</th>
                                    <th>Sent On</th>
                                    <th>Reply</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for message in received_messages %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ message.sender }}</td>
                                    <td>{{ message.message }}</td>
                                    <td>{{ message.created_at }}</td>
                                    <td>
                                        {% if message.reply %}
                                            {{ message.reply }}
                                        {% else %}
                                            <form method="post">
                                                {% csrf_token %}
                                                <input type="hidden" name="message_id" value="{{ message.id }}">
                                                <textarea name="reply" rows="2" cols="30"></textarea>
                                                <button type="submit" class="btn btn-sm btn-primary">Reply</button>
                                            </form>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
</section>
{% endblock content %}

{% block custom_js %}
<script>
    $(document).ready(function(){
        $(".reply_open_modal").click(function(){
            var id = $(this).val();
            var name = $(this).parents("tr").children("td:eq(1)").text();
            $("#reply_name").text(name);
            $("#id").val(id);
        });

        $("#reply_btn").on("click", function(){
            var id = $("#id").val();
            var reply = $("#reply_message").val();

            $.ajax({
                url: "{% url 'employer_receive_message' %}",
                type: 'POST',
                data: {
                    id: id,
                    reply: reply
                }
            }).done(function(response){
                if (response == "True"){
                    alert("Reply Sent");
                    location.reload();
                } else {
                    alert("Reply Could Not Be Sent");
                }
            }).fail(function(response){
                alert("Error Occurred.");
            });
        });
    });
</script>
{% endblock custom_js %}

office_management_system/main_app/templates/employer_template/employer_edit_message.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>
                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Edit Message"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

office_management_system/main_app/templates/employer_template/employer_manage_tasks.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Organizer</th>
                                    <th>Due Date</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for task in tasks %}
                                <tr>
                                    <td>{{ task.title }}</td>
                                    <td>{{ task.description }}</td>
                                    <td>{{ task.manager }}</td>
                                    <td>{{ task.due_date }}</td>
                                        <td>
                                            {% if task.completed %}
                                            <span class="badge badge-success">Completed</span>
                                        {% else %}
                                            <span class="badge badge-danger">In Progress</span>
                                        {% endif %}
                                        </td>
                                    <td>
                                        {# Edit Button #}
                                        <a href="{% url 'update_employer_task' task.id %}" class="btn btn-info">Completed</a>
                                    </td>

                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}


office_management_system/main_app/templates/employer_template/employer_view_notification.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>


                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">






                        <div class="form-group table">
              <table class="table table-bordered">
                  <tr>
                      <th>#</th>
                      <th>Sender</th>
                      <th>Date</th>
                      <th>Message</th>
                  </tr>
                  {% for notification in  notifications %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{notification.sender}}</td>
                        <td>{{notification.created_at}}</td>
                        <td>{{notification.message}}</td>
                    </tr>
                  {% endfor %}
              </table>
                        </div>

                    </div>

                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}



office_management_system/main_app/templates/employer_template/filter_participants_template.html
<div class="card card-dark">
    <div class="card-header">
        <h3 class="card-title">Filter Participants</h3>
    </div>
    <div class="card-body">
        <form id="filter-participants-form" method="post" action="{% url 'create_meeting_employer' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_user_type">User Type</label>
                {{ filter_form.user_type }}
            </div>
            <div class="form-group">
                <label for="id_department">Department</label>
                {{ filter_form.department }}
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>
    </div>
</div>